server:
  port: 8084
spring:
  zipkin:
    base-url: http://192.168.0.50:9411
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mariane-muniz/all-server-config
          searchPaths: '{application}/{profile}'
  devtools:
    add-properties: off
logging:
  level:
    root: info
  file:
    max-history: 1
    max-size: 10MB
    name: /home/scott/Projects/logs/configuration.log

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

endpoints:
  shutdown:
    enabled: true